/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Mateus
 */
public class JFGame extends javax.swing.JFrame {

    /**
     * Creates new form JFGame
     */
    public JFGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBoard = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Velha");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panBoard.setBackground(new java.awt.Color(224, 224, 224));
        panBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Chiller", 1, 100)); // NOI18N
        jButton2.setText("X");
        jButton2.setToolTipText("");
        jButton2.setBorder(null);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panBoard.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 150, 120));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Chiller", 1, 100)); // NOI18N
        jButton3.setText("O");
        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panBoard.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, 120));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Chiller", 1, 100)); // NOI18N
        jButton4.setText("X");
        jButton4.setToolTipText("");
        jButton4.setBorder(null);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panBoard.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 150, 120));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Chiller", 1, 100)); // NOI18N
        jButton6.setText("X");
        jButton6.setToolTipText("");
        jButton6.setBorder(null);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panBoard.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, 120));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Chiller", 1, 100)); // NOI18N
        jButton7.setText("X");
        jButton7.setToolTipText("");
        jButton7.setBorder(null);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panBoard.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 150, 120));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Chiller", 1, 100)); // NOI18N
        jButton8.setText("X");
        jButton8.setToolTipText("");
        jButton8.setBorder(null);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panBoard.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 150, 120));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Chiller", 1, 100)); // NOI18N
        jButton9.setText("X");
        jButton9.setToolTipText("");
        jButton9.setBorder(null);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panBoard.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 150, 120));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Chiller", 1, 100)); // NOI18N
        jButton10.setText("X");
        jButton10.setToolTipText("");
        jButton10.setBorder(null);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panBoard.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 150, 120));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Chiller", 1, 100)); // NOI18N
        jButton11.setText("X");
        jButton11.setToolTipText("");
        jButton11.setBorder(null);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panBoard.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 150, 120));

        getContentPane().add(panBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

 
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel panBoard;
    // End of variables declaration//GEN-END:variables
}
